### PR TITLE
Moogle Tweaks II

### PR DESCRIPTION
**Pull request by MogTheMoogle**
Tweaking stats and overhauling their weapon perks- guns aren't the only weapons that they're good with.

STATS
- Weaknesses are tweaked (-5% Physical, -5% Radiation and -20% Shadow)
- Cosmic resist is higher than before (30%)

WEAPONS
- Firearms nerfed to +5% Damage, +1% Crit
- Broadswords, Shortswords, Staves and Wands gain 5% damage
- Rapiers, Spears, Energy Weapons, Pistols and Machine Pistols gain 10% damage, +2% Crit

MISC
- More reformatting.

### CODE REVIEW

**Comment by MogTheMoogle** [comment]
Turns out I broke something. I'll figure out what went wrong and reopen it when it's patched to not break everything.

**Comment by MogTheMoogle** [comment]
Managed to fix it on my end.

**Comment by sayterdarkwynd** [comment]
why would a moogle be good with guns? they are pre-warp critters that live in caves.

**Comment by MogTheMoogle** [comment]
These ones are based off Final Fantasy Tactics Advance and A2- the Ivalice Moogles.
There's the gunner (Fusilier) class for them.

**Pull request merged**
