### PR TITLE
irken race support

### PR DESCRIPTION
**Pull request by commanderdarkkirby**
just wanted to submit a support for the irkens so they have their own stats. just trying to make a more up to date frackin irkens

### CODE REVIEW

**Comment by KH007** [comment]
Don't forget to alter the .metadata and Interface files.

**Comment by commanderdarkkirby** [comment]
oh whoops, hold on

**Comment by commanderdarkkirby** [comment]
> Don't forget to alter the .metadata and Interface files.

wait, what Interface files exactly?

**Comment by KH007** [comment]
> > Don't forget to alter the .metadata and Interface files.
> 
> wait, what Interface files exactly?

Take a look at the one I did where I added Lutrin support to Frackin.
Specifically, the one involving the Tricorder's species info window.

**Comment by commanderdarkkirby** [comment]
ok there, i did both of those...

**Comment by KH007** [comment]
I don't see it on this end. You seeing it on your end?

**Comment by commanderdarkkirby** [comment]
yes i'am...i just did it.

**Comment by KH007** [comment]
Might want to push that commit into your branch so that we can see it; I'm still only seeing the one commit from earlier when you opened this pull request.

**Comment by commanderdarkkirby** [comment]
uhh...oh my gosh...i don't even know how to use this stuff...

**Comment by KH007** [comment]
It's as simple as making a commit into your own branch and then confirming it. That's how I kept on updating the pull request I made.

so, just edit the files in question.

**Comment by commanderdarkkirby** [comment]
uhhh....ummm....ok then? oh my gosh, i've never used github like this before...i just want to make a more up to date frackin irkens....

**Comment by KH007** [comment]
It's cool; we all have a first time.

**Comment by commanderdarkkirby** [comment]
ok, i think i did it

**Comment by KH007** [comment]
Well, that's a roundabout way, but as long as Sayter confirms all three, that should work.

**Pull request merged**
