### PR TITLE
Lucario protopatch

### PR DESCRIPTION
**Pull request by XDgierman**
Proto-Poison resistance added + cut down on description.

### CODE REVIEW

**Comment by XDgierman** [comment]
I've decided to remove all stat description from the lucario.species.patch, due to the limits of the description box (the list was too lenghty for the box). All the description about the race is written on the Lucario Race mod page.

**Comment by Zancuno** [comment]
May want to remove the version number update, got informed of that recently, as the FU team will update the version number when they prepare another release. Also I agree with the resistance rather than immunity for proto-poison due to it being an unknown factor, even though they are immune to poison.

**Comment by XDgierman** [comment]
> May want to remove the version number update, got informed of that recently, as the FU team will update the version number when they prepare another release.

Oh, I weren't aware of that. Droppin' that change now.

**Comment by sayterdarkwynd** [comment]
that wont work. Proto immunity is either on, or off. It's not a percentage value. Proto poison is resisted by poison resistance, if i recall

**Comment by Zancuno** [comment]
https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/stats/effects/fu_immunityeffects/protoimmunity.statuseffect

Just checked for ya, yeah it's an on of off thing although I worry making the lucario add it now to FR before the merger might result in a (Missing key "protoImmunity", no such effect get) if FU is not installed. Which may either crash or cause the patch to fail. I should probably get a copy of this PR and run it on a save without FU.

Granted I found the file you was referring to Sayter
https://github.com/sayterdarkwynd/FrackinUniverse/blob/master/stats/effects/fu_weathereffects/new/protoworld/protoweather.statuseffect

So all we have to do is give the lucario poison resistance based on that file.

**Comment by gamrguy** [comment]
Don't worry about stats being "missing", the game doesn't require stats to be defined specifically beforehand! In fact, trying to read an unset stat simply returns `0`.

It's _status effects_ that you need to watch out for.

**Comment by sayterdarkwynd** [comment]
minimum resistance to be immune to proto is 45 poison resist, which is slightly above the threshold where an equal weakness is important

**Comment by XDgierman** [comment]
The weaknenses were already added, the proto poison was the thing that we didn't count on. Changed the incorrect immunity for the poisonResistance, making the race immune to normal proto poison status and not immune to extreme proto poison, on what I understand.

**Comment by sayterdarkwynd** [comment]
conflicts in the meta.

**Comment by Zancuno** [comment]
Save the changes you made to a .txt document for now, close the PR, update your fork of FR, apply changes, open PR again. FR updated so this is conflicting atm

**Pull request closed without merging**
