### PR TITLE
Everis race support.

### PR DESCRIPTION
**Pull request by RutheniumIX**
Here's the races support for Everis. If possible, could the following be verified/added?
>Everis resistance to cold climates should only apply for planets on temperate stars, aka tier 3-4 planets.
>If there's a way to give Everis a natural tech that lets them attack with their claws that would be cool too, though it's not necessary and I understand if it shouldn't be implemented. Thanks in advance!

Also, wasn't too sure whether I should have just added the patches or inserted the files that I changed. I did the latter, so only 3 files are changed to support Everis. Not sure why it's saying there's over 8,000 additions, I hope I didn't do something wrong.

Edit: I did insert the Everis changes (in the config and .metadata files) in the place that they'd fit in alphabetically, which shifted everything after them downward. Maybe that did it?

### CODE REVIEW

**Comment by sayterdarkwynd** [comment]
Nope. raceEffects.config *must* be a patch file update.

**Comment by sayterdarkwynd** [comment]
im not sure what it is you are doing incorrectly. Minor thing, for sure. 

The PR should be highlighting only your changes to the file, not the entire related file. Not a huge deal, I can manually add this info in to make sure there arent issues.

**Comment by sayterdarkwynd** [comment]
K i manually added your additions into my files just to be safe. Will close this ticket. thanks.

**Comment by RutheniumIX** [comment]
Okay, thanks! Will keep that in mind for future requests if any.

**Pull request closed without merging**
