### PR TITLE
Lucario race support

### PR DESCRIPTION
**Pull request by XDgierman**
This is my first pull so correct me if I did something wrong.
I'm commiting race support for [Lucario race](https://community.playstarbound.com/resources/lucario-race.4940/) that is made by [Zancuno](https://community.playstarbound.com/members/zancuno.590896/).
I hope that I made the scripting right, and I hope it will work!

### CODE REVIEW

**Comment by XDgierman** [comment]
Ok, I got in contact with mod creator of Lucario race, so I will make now some traits changes basing on suggestions of creator, but I need help with "berserk perk" that Zancuno suggested (
The More Damage you Take, the more Dangerous you become (modified)
4/4 health: +0 damage
3/4 health: +5 damage
2/4 health +10 damage -5 armor
1/4 health +10 damage -10 armor
)

**Comment by adamkad1** [comment]
Maybe put 15 damage at 1/4? Might be a bit powerfull but the free armor reduction seems cheap

**Comment by XDgierman** [comment]
I'm thinking about modifying Apex primial bonus to make it, but I have hard to understand the code of it and how to modify it to Lucario use

**Comment by XDgierman** [comment]
Ok, I found out that [/scripts/fr_weaponscripts/healthybonus.lua](https://github.com/sayterdarkwynd/FrackinRaces/blob/master/scripts/fr_weaponscripts/healthybonus.lua) is an perfect base for "berserkBonus", but I dont know how to make it work. Some help?

**Comment by ParrotParrot** [comment]
That script is used as an helper call from the weaponscripts that call for it, and only works if health is above a threshold rather than below it. It should be hard to write a mirrored script and add it as an helper script and call it without context from the race's weaponscripts, but there's always the chance that it will not work.

**Comment by XDgierman** [comment]
Maybe @gamrguy would help me with that (cuz' he made that apexRageBonus), but i'm starting to understand how the code of apexRageBouns works.

**Pull request merged**
