### PR TITLE
Frackin' Mod - Pony Modpack

### PR DESCRIPTION
**Pull request by NarratorLair**
Adding ponies. While playtesting couldn't be done, I feel that those bonuses and support of The Pony Modpack can be introduced there.

### CODE REVIEW

**Comment by Kherae** [comment]
showed this to the mod's author, and this was his rather funny response: 
> which utter retard made my races not die on contact with fire
>lore wize ponex are 95% erchius fuel
>i mean, i trust yall to know what you are doing
>still keep in mind ponex are 95% erchius fuel

**Comment by NarratorLair** [comment]
Well, I still can't make that so fire kills, but here comes 100% weakness to fire.

**Comment by NarratorLair** [comment]
All right, I reckon that's about all nerfs and buffs. Mostly to the speed

**Comment by sayterdarkwynd** [comment]
sure, why not

**Pull request merged**
